#!/usr/bin/env python3
"""
langman - Generated by GTK App Builder, app made by soil
"""

import gi
import subprocess
import sys

gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk, GdkPixbuf, Gio, Pango

class langmanWindow(Gtk.ApplicationWindow):
    def __init__(self, app):
        super().__init__(application=app)
        self.set_default_size(550, 400)
        self.set_title("Language Choose")
        
        self.page_widgets = {}
        
        self._build_ui()
        
    def _build_ui(self):
        self.stack = Gtk.Stack()
        self.stack.set_transition_type(Gtk.StackTransitionType.SLIDE_LEFT_RIGHT)
        self.add(self.stack)
        
        main_page = Gtk.Fixed()
        self.stack.add_named(main_page, "Main Page")
        self.page_widgets["Main Page"] = {}
        
        w_label_140338375462848 = Gtk.Label(label="Choose a language")
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_label_140338375462848.override_font(font_desc)
        main_page.put(w_label_140338375462848, 205, 100)
        self.page_widgets["Main Page"]["label_140338375462848"] = w_label_140338375462848
        
        w_button_140338114367104 = Gtk.Button(label="English")
        w_button_140338114367104.set_size_request(87, 35)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114367104.override_font(font_desc)
        w_button_140338114367104.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman english']))
        main_page.put(w_button_140338114367104, 68, 166)
        self.page_widgets["Main Page"]["button_140338114367104"] = w_button_140338114367104
        
        w_button_140338114404992 = Gtk.Button(label="Español")
        w_button_140338114404992.set_size_request(90, 37)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114404992.override_font(font_desc)
        w_button_140338114404992.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman spanish']))
        main_page.put(w_button_140338114404992, 172, 165)
        self.page_widgets["Main Page"]["button_140338114404992"] = w_button_140338114404992
        
        w_button_140338114405376 = Gtk.Button(label="Português")
        w_button_140338114405376.set_size_request(94, 37)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114405376.override_font(font_desc)
        w_button_140338114405376.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman portuguese']))
        main_page.put(w_button_140338114405376, 275, 164)
        self.page_widgets["Main Page"]["button_140338114405376"] = w_button_140338114405376
        
        w_button_140338114397952 = Gtk.Button(label="Deutsch")
        w_button_140338114397952.set_size_request(94, 37)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114397952.override_font(font_desc)
        w_button_140338114397952.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman german']))
        main_page.put(w_button_140338114397952, 382, 164)
        self.page_widgets["Main Page"]["button_140338114397952"] = w_button_140338114397952
        
        w_button_140338114407744 = Gtk.Button(label="Français")
        w_button_140338114407744.set_size_request(94, 37)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114407744.override_font(font_desc)
        w_button_140338114407744.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman french']))
        main_page.put(w_button_140338114407744, 382, 208)
        self.page_widgets["Main Page"]["button_140338114407744"] = w_button_140338114407744
        
        w_button_140338114408512 = Gtk.Button(label="Italiano")
        w_button_140338114408512.set_size_request(94, 37)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114408512.override_font(font_desc)
        w_button_140338114408512.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman italian']))
        main_page.put(w_button_140338114408512, 275, 208)
        self.page_widgets["Main Page"]["button_140338114408512"] = w_button_140338114408512
        
        w_button_140338114409152 = Gtk.Button(label="Русский")
        w_button_140338114409152.set_size_request(94, 37)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114409152.override_font(font_desc)
        w_button_140338114409152.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman russian']))
        main_page.put(w_button_140338114409152, 171, 208)
        self.page_widgets["Main Page"]["button_140338114409152"] = w_button_140338114409152
        
        w_button_140338114410368 = Gtk.Button(label="Türkçe")
        w_button_140338114410368.set_size_request(94, 37)
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_button_140338114410368.override_font(font_desc)
        w_button_140338114410368.connect('clicked', lambda btn: subprocess.Popen(['bash', '-c', 'lxterminal --command pkexec langman turkish']))
        main_page.put(w_button_140338114410368, 66, 208)
        self.page_widgets["Main Page"]["button_140338114410368"] = w_button_140338114410368
        
        w_label_140338114410560 = Gtk.Label(label="After the terminal window closes,")
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_label_140338114410560.override_font(font_desc)
        main_page.put(w_label_140338114410560, 148, 258)
        self.page_widgets["Main Page"]["label_140338114410560"] = w_label_140338114410560
        
        w_label_140338114412160 = Gtk.Label(label="restart ur pc!")
        font_desc = Pango.FontDescription()
        font_desc.set_size(12 * Pango.SCALE)
        w_label_140338114412160.override_font(font_desc)
        main_page.put(w_label_140338114412160, 221, 279)
        self.page_widgets["Main Page"]["label_140338114412160"] = w_label_140338114412160
        
        self.stack.set_visible_child(main_page)
        self.show_all()

class langmanApp(Gtk.Application):
    def __init__(self):
        super().__init__(application_id='com.unstablesoil.langman',
                         flags=Gio.ApplicationFlags.FLAGS_NONE)
        
    def do_activate(self):
        win = langmanWindow(self)
        win.show_all()

def main():
    app = langmanApp()
    return app.run(sys.argv)

if __name__ == '__main__':
    main()
