name: Build OmegaLinux NEXT ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: get sources
        uses: actions/checkout@v4

      - name: install archiso and dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S archiso git sudo grub syslinux squashfs-tools libisoburn libarchive dosfstools e2fsprogs mtools erofs-utils arch-install-scripts --noconfirm

      - name: build iso
        run: |
          chmod +x Build.sh
          ./Build.sh

      - name: upload iso
        uses: actions/upload-artifact@v4
        with:
          name: OmegaLinuxNEXT-Latest
          path: ISOs/*.iso
          if-no-files-found: error
          retention-days: 7
